### PR TITLE
feat: renterd config evaluation

### PR DESCRIPTION
**Pull request by alexfreska**
- The renterd configuration page now recommends specific changes to settings to match with more hosts.
- Configuration settings that the user has not modified will be kept in sync with remote values that change (renterd & hostd).
- Fixed a few other related bugs.
Screenshot 2024-04-25 at 3 47 10 PM
Screenshot 2024-04-25 at 3 46 58 PM
Screenshot 2024-04-25 at 3 46 51 PM
Screenshot 2024-04-25 at 3 46 39 PM
Screenshot 2024-04-25 at 4 25 47 PM

### CODE REVIEW

**Comment by alexfreska** [comment]
* **#609** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/609?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alexfreska and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ChrisSchinnerl** [comment]
Love the recommendations. Only criticism I got is the amount of text we are hitting a user with. I'm really not great when it comes to UX myself but I wonder if we can make this a bit more concise.

**Comment by alexfreska** [comment]
> Love the recommendations. Only criticism I got is the amount of text we are hitting a user with. I'm really not great when it comes to UX myself but I wonder if we can make this a bit more concise.

@ChrisSchinnerl yep agreed, I refined the UX a bit, let me know if feels better.

**Comment by ChrisSchinnerl** [comment]
> > Love the recommendations. Only criticism I got is the amount of text we are hitting a user with. I'm really not great when it comes to UX myself but I wonder if we can make this a bit more concise.
> 
> @ChrisSchinnerl yep agreed, I refined the UX a bit, let me know if feels better.

That's a lot better 👍

**Review by n8maninger — APPROVED** [review]

**Pull request merged**
