### PR TITLE
refactor(explorer-e2e): adjust address amount test

### PR DESCRIPTION
**Pull request by telestrial**

### CODE REVIEW

**Comment by telestrial** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/812?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#812** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/812?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#811** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/811?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @telestrial and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alexfreska — COMMENTED** [review]
What does removing this value do?

**Comment by telestrial** [comment]
This test was failing because there's some rounding inconsistency here that I don't completely understand. I don't believe it comes from any adjustments I've made. The rendered amount was flipping between 1.262 and 1.261 MS. I do think it's probably worth it to create a task to investigate but I'm not sure it's worth it to pin the success of this test on. Definitely willing to defer to your wisdom on that, though!

**Review by alexfreska — APPROVED** [review]
Interested to investigate why the number would be changing, but do merge if it stabilizes the tests while the focus is elsewhere.

**Comment by telestrial** [comment]
Taking a gander at this some more, I was wrong about my assumption that it was a rounding issue. I think it is that this address is being "spent down" from when I first wrote the test. That's a good reason not to try to test this value--that it's going to change over time.

**Comment by telestrial** [comment]
### Merge activity

* **Nov 19, 2:29 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/SiaFoundation/web/812).

**Pull request merged**
