### PR TITLE
feat: walletd rescan

### PR DESCRIPTION
**Pull request by alexfreska**
- Address generation and addition dialogs now have an option to rescan from a specified height.
- There is now a dedicated rescan dialog that can be opened from the wallet list and wallet context menus.
- Rescan progress and status including errors is now shown in a sticky status bar.

Screenshot 2024-04-04 at 11 18 40 AM

Screenshot 2024-04-04 at 10 51 46 AM

Screenshot 2024-04-04 at 10 51 48 AM

Screenshot 2024-04-04 at 10 20 27 AM

### CODE REVIEW

**Comment by alexfreska** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/566?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#566** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/566?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#565** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/565?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#563** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/563?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#564** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/564?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#562** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/562?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alexfreska and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by n8maninger** [comment]
I’m not sure we should enable this or maybe hide it behind an advanced flag. What do you think?

**Comment by alexfreska** [comment]
> I’m not sure we should enable this or maybe hide it behind an advanced flag. What do you think?

@n8maninger The toggle defaults to OFF and in this state it does not show the index input or the warning below.

Do you mean completely disable this feature by default via a daemon startup config value? Or do you mean just tucking it away a bit more than it is - maybe you have to expand the advanced section to even see the toggle?

**Comment by n8maninger** [comment]
I don't know what would be best. My concern is that users will input a number in the index field without really understanding what it does and then be confused when their wallet doesn't show transactions. I meant tucking it away a bit more over a config flag or anything like that. It just needs to be very clear about the portion of blockchain that won't be scanned and the ramifications of that.

**Pull request merged**
