### PR TITLE
fix(renterd): config fields blank sia central

### PR DESCRIPTION
**Pull request by alexfreska**
- Fixed an issue where configured settings would show as blank when the Sia Central API (used for network averages) was down. https://github.com/SiaFoundation/renterd/issues/1601
- Fixed an issue where SiacoinField was depending on the siaCentral setting rather than the active exchange rate API.
- Refactoring
  - Refactored the internal autopilotInfo usage to be more clear.
  - Refactored useResources and resources into one file.

### CODE REVIEW

**Comment by alexfreska** [comment]
* **#767** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/767?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alexfreska and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by telestrial — APPROVED** [review]
If I understand the change correctly: do we currently tell the user that the API is down? They may have expectations about what they're seeing and be confused when they don't see what they expect.

**Comment by alexfreska** [comment]
> If I understand the change correctly: do we currently tell the user that the API is down? They may have expectations about what they're seeing and be confused when they don't see what they expect.

@telestrial SiacoinFields (the ones that show both siacoin input and the fiat input below) gracefully degrade, meaning they do not show the fiat input if the exchange rate is not available.
The renterd pinned configuration fields get completely disabled and show the user a warning message stating that the API is required for the feature.

It would probably be a good improvement to show a similar warning on SiacoinField. I'll create an issue: https://github.com/SiaFoundation/web/issues/777

**Comment by alexfreska** [comment]
### Merge activity

* **Oct 11, 1:53 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/SiaFoundation/web/767).

**Pull request merged**
