### PR TITLE
feat(renterd): files explorer multiselect and batch delete

### PR DESCRIPTION
**Pull request by alexfreska**
- The directory-based file explorer now supports multiselect across any files and directories.
- The directory-based file explorer multiselect menu now supports batch deletion of selected files and directories.
- Navigating into a directory in the file explorer is now by clicking on the directory name rather than anywhere on the row.
- The "all files" file explorer now supports multiselect across any files.
- The "all files" file explorer multiselect menu now supports batch deletion of selected files.

### CODE REVIEW

**Comment by alexfreska** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/785?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#785** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/785?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#784** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/784?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alexfreska and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by telestrial — APPROVED** [review]
This may seem frictional to my last comment on multi-select about inviting users into the feature: if users must now click on the directory name exactly, is there an invitation to that? underlined or onHover underlined or something to that effect?

It may end up that some of the triggers/actions a user takes within this framework may need to be adjusted to feel more comfortable. Might be worth it to hit the discord when this lands and garner some feedback around what feels natural.

**Comment by alexfreska** [comment]
@telestrial agreed, I think after applying this feature to most of the tables we should review them all and make some refinements. I already made some changes (moving the selection from checkboxes to entire row) when adding to the file explorer because it felt more intuitive and consistent, but a few of the upcoming tables have other interacts when clicking a row that will need to be moved - so I think there will be some refinements to make once the first pass is done and have an inventory of all the interactions to support.
To answer your question about the discoverability, yes the text is underlined on hover. Another good addition may be double click to open a directory similar to the OS finder behaviour. Also matching system ctrl+select behaviour a little more closely. I will do some follow on improvements and once a version is out I agree the I'm sure users will have thoughts for us.

**Comment by alexfreska** [comment]
### Merge activity

* **Oct 30, 1:59 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/SiaFoundation/web/785).

**Pull request merged**
