### PR TITLE
fix: pluralize add tests

### PR DESCRIPTION
**Pull request by alexfreska**
- Fixed a bug in the pluralize helper, added tests.

### CODE REVIEW

**Comment by alexfreska** [comment]
* **#710** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/710?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#712** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/712?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @alexfreska and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by telestrial** [comment]
@alexfreska Is this change mainly getting at this "children" example? What was the original undesirable behavior?

**Comment by alexfreska** [comment]
> @alexfreska Is this change mainly getting at this "children" example? What was the original undesirable behavior?

@telestrial not specifically, I just added exhaustive tests for all usage patterns. It actually returned a malformed string for 3 of  the test cases, so just generally not correct. I "checked" it in the app, should have had these tests from the start. Results with the old method:
Screenshot 2024-08-30 at 1 50 30 PM

**Comment by telestrial** [comment]
> It actually returned a malformed string for 3 of the test cases, so just generally not correct.

Gotcha. Yeah. I think this is a matter of scope: how comprehensive should this be? If we want an all-purpose pluralization function to use freely anywhere and everywhere, it may make sense to use an npm library. There are so so many edge cases and novel rules about pluralization in the English language. Words that add "s" or "es", ones that do neither, ones that just use a different ending altogether, and more. It would probably take a pretty large engineering effort to cover them all. If instead we're looking to cover this vertical of pluralization for specific words in our apps--hosts, renters, etc, it may make sense to do something a bit more explicit: a map of our known needed words and a function that handles that data structure. 

For the comprehensive route: I've used [this](https://github.com/plurals/pluralize) to some success in other projects. 

Even that library won't cover everything, though. This is a deceivingly complex problem in the English language.

**Review by telestrial — APPROVED** [review]

**Comment by alexfreska** [comment]
> > It actually returned a malformed string for 3 of the test cases, so just generally not correct.
> 
> Gotcha. Yeah. I think this is a matter of scope: how comprehensive should this be? If we want an all-purpose pluralization function to use freely anywhere and everywhere, it may make sense to use an npm library. There are so so many edge cases and novel rules about pluralization in the English language. Words that add "s" or "es", ones that do neither, ones that just use a different ending altogether, and more. It would probably take a pretty large engineering effort to cover them all. If instead we're looking to cover this vertical of pluralization for specific words in our apps--hosts, renters, etc, it may make sense to do something a bit more explicit: a map of our known needed words and a function that handles that data structure.
> 
> For the comprehensive route: I've used [this](https://github.com/plurals/pluralize) to some success in other projects.
> 
> Even that library won't cover everything, though. This is a deceivingly complex problem in the English language.

I wanted to avoid pulling in a dependency, especially one with a dictionary - this API circumvents the complexity by simply having the caller provide the singular and plural words. The benefit being it abstracts all the nested ternary stuff.

**Comment by telestrial** [comment]
> I wanted to avoid pulling in a dependency, especially one with a dictionary - this API circumvents the complexity by simply having the caller provide the singular and plural words. The benefit being it abstracts all the nested ternary stuff.

Totally agree on the library. Just outlining options, even the less great ones. I think your solution should work well but we may find edge cases over time that challenge the parameters here. Maybe not, though! There's so many weird rules to remember/know them all.

**Comment by alexfreska** [comment]
> > I wanted to avoid pulling in a dependency, especially one with a dictionary - this API circumvents the complexity by simply having the caller provide the singular and plural words. The benefit being it abstracts all the nested ternary stuff.
> 
> Totally agree on the library. Just outlining options, even the less great ones. I think your solution should work well but we may find edge cases over time that challenge the parameters here. Maybe not, though! There's so many weird rules to remember/know them all.

@telestrial 👍🏼 yep we may need to adjust the options as we go. Oddly I couldn't find thaaat many places we needed pluralization - maybe just my grepping didn't catch em.

**Pull request merged**
