### PR TITLE
fix humanUnits for hostd using 1e7 for millions

### PR DESCRIPTION
**Pull request by iuri-gg**
hostd settings is showing incorrect number for base rpc price and Sector access price. It's off by 10 due to using 1e7 instead of 1e6 for calculating millions

### CODE REVIEW

**Comment by alexfreska** [comment]
@iuri-gg hey thank you so much for finding this bug and your contribution!

could you add a changeset so that your fix shows up in the next version's change log?

Locally run `npx changset` select `hostd`, select patch change, and then add a description such as:
```
Fixed an issue where the base RPC and sector access price calculation was off by 10.
```
and then commit the file to this PR.

**Comment by alexfreska** [comment]
@iuri-gg also while you are in this file, could you fix the comment, it says PRC instead of RPC 😄

**Comment by iuri-gg** [comment]
@alexfreska Thanks for the feedback. Hope I got it correctly this time 🤞

**Comment by alexfreska** [comment]
> @alexfreska Thanks for the feedback. Hope I got it correctly this time 🤞

@iuri-gg thats perfect. I will run the CI and double check the values.

**Comment by alexfreska** [comment]
@iuri-gg looks like you need to update a few tests - they are currently checking for the incorrect values. 
https://github.com/SiaFoundation/web/actions/runs/7533680654/job/20506787267?pr=466#step:7:124
Screenshot 2024-01-15 at 12 32 54 PM

To run the `hostd` tests:
```
npx test hostd
```

**Comment by iuri-gg** [comment]
dont know why `package-lock.json` got updated. is that expected? if I run npm install, it updates the `package-lock.json`

**Comment by alexfreska** [comment]
> dont know why `package-lock.json` got updated. is that expected? if I run npm install, it updates the `package-lock.json`

yeah thats good, a previous PR likely missed an update

**Comment by alexfreska** [comment]
@iuri-gg merging, thank you! 🚀 Your change will show up in the release PR shortly: https://github.com/SiaFoundation/web/pull/465

Note: The CI failed because the package-lock change triggered a build across all projects, and external contributors do not have permission to build the website, which is the only project that failed, everything else passed!

**Pull request merged**
