### PR TITLE
fix(explorer): fix network request calls when navigating to block by height

### PR DESCRIPTION
**Pull request by telestrial**

### CODE REVIEW

**Comment by telestrial** [comment]
* **#800** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/800?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#799** <a href="https://app.graphite.dev/github/pr/SiaFoundation/web/799?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @telestrial and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alexfreska — APPROVED** [review]
Looks good, good candidate to add in the tests.

**Comment by telestrial** [comment]
> Looks good, good candidate to add in the tests.

That's exactly how I found it. Wrote the test and got the errant result.

**Comment by telestrial** [comment]
### Merge activity

* **Nov 5, 2:17 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/SiaFoundation/web/799).

**Pull request merged**
