### PR TITLE
add net address and uptime to node profile

### PR DESCRIPTION
**Pull request by alexfreska**
- The renterd and hostd node profile details now include uptime.

Screenshot 2024-02-14 at 2 54 54 PM

### CODE REVIEW

**Comment by n8maninger** [comment]
Net address doesn’t really make sense for `renterd` imo

**Review by ChrisSchinnerl — CHANGES_REQUESTED** [review]
I agree with Nate. NetAdress doesn't make sense for renters imo.

**Comment by alexfreska** [comment]
@n8maninger @ChrisSchinnerl yeah hmm, I guess that change was mainly for me or others who use the hosted UI with multiple nodes - I was just getting confused as to which node I was looking at. I think `hostd` has a config value for "name", does renterd have this? I could simply show the name, if set.

**Comment by ChrisSchinnerl** [comment]
@alexfreska The bus doesn't have a name but the worker api got a `/id` endpoint that exposes a name that you can give your worker to distinguish between them in a cluster setup.

**Comment by alexfreska** [comment]
@ChrisSchinnerl @n8maninger  I've removed the net address, this is now just uptime.

**Review by n8maninger — APPROVED** [review]

**Pull request merged**
